// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXoG6fIZiFtHjsmepxqX55Maev_w-x0K4',
    appId: '1:831470219518:web:a2bb94fb1f5bb31187b5af',
    messagingSenderId: '831470219518',
    projectId: 'chess-game-4477e',
    authDomain: 'chess-game-4477e.firebaseapp.com',
    storageBucket: 'chess-game-4477e.firebasestorage.app',
    measurementId: 'G-BYW045K2R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLRNaH2ZZEfnLODG06iAuVsuMUHUOFphk',
    appId: '1:831470219518:android:849bb30014b0326087b5af',
    messagingSenderId: '831470219518',
    projectId: 'chess-game-4477e',
    storageBucket: 'chess-game-4477e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCl-FoAJtLeFDLOBylhg1-ZW1HpXFngg',
    appId: '1:831470219518:ios:7e45fce1cdfe366887b5af',
    messagingSenderId: '831470219518',
    projectId: 'chess-game-4477e',
    storageBucket: 'chess-game-4477e.firebasestorage.app',
    iosBundleId: 'com.example.flutterChessApp',
  );
}
