import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_chess_app/firebase_options.dart';
import 'package:flutter_chess_app/services/auth_service.dart';
import 'package:get/get.dart';
import 'theme/app_theme.dart';
import 'views/login_view.dart';
import 'views/home_view.dart';
import 'views/main_view.dart';
import 'views/game_view.dart';
import 'views/profile_view.dart';
import 'views/leaderboard_view.dart';
import 'views/friends_view.dart';
import 'utils/dependency_injection.dart';
import 'controllers/theme_controller.dart';
import 'views/splash_screen.dart';
import 'views/settings_view.dart';
import 'views/match_history_view.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // IMPORTANT: You must replace this with your actual Firebase Options
    // generated by `flutterfire configure`.
    // If you haven't run that, this will fail on real devices.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform
    );
    DependencyInjection.init();
    // Get.put(ThemeController(), permanent: true);
    // Get.put(AuthService(), permanent: true);
  } catch (e) {
    debugPrint("Firebase Initialization Warning: $e");
    debugPrint("Ensure you have added google-services.json / GoogleService-Info.plist or used FlutterFire CLI.");
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // ThemeController is put in DependencyInjection.init()
    final ThemeController themeController = Get.find<ThemeController>();
    return Obx(
      () => GetMaterialApp(
        title: 'Chess Master',
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: themeController.isDarkMode ? ThemeMode.dark : ThemeMode.light,
        initialRoute: '/splash',
        // AuthService will redirect to /home if authenticated
        getPages: [
          GetPage(name: '/splash', page: () => const SplashScreen()),
          GetPage(name: '/login', page: () => LoginView()),
          GetPage(name: '/home', page: () => const MainView()),
          GetPage(name: '/game', page: () => GameView()),
          GetPage(name: '/profile', page: () => ProfileView()),
          GetPage(name: '/leaderboard', page: () => LeaderboardView()),
          GetPage(name: '/friends', page: () => FriendsView()),
          GetPage(name: '/settings', page: () => const SettingsView()),
          GetPage(name: '/match_history', page: () => MatchHistoryView()),
        ],
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}
